FROM node:16-alpine

WORKDIR /app

# Install xsel so that serve doesn't try to copy to clipboard
RUN apk add --no-cache xsel

COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build"]
